repos:
  - repo: local
    hooks:
      - id: commitizen-check
        name: commitizen check
        entry: uv run python -m commitizen check --commit-msg-file
        language: system
        stages: [commit-msg]

      - id: detect-secrets
        name: detect secrets
        entry: uv run detect-secrets-hook --baseline .secrets.baseline
        language: system
        stages: [pre-commit]